// <auto-generated />
using System;
using Contacts.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Contacts.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123134653_PhoneNumberPositionManyToMany")]
    partial class PhoneNumberPositionManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contacts.Domain.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_account_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_account_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_account_updated_by_id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Handbook.Handbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_handbook");

                    b.ToTable("handbook", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Handbook.HandbookItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HandbookId")
                        .HasColumnType("integer")
                        .HasColumnName("handbook_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_handbook_item");

                    b.HasIndex("HandbookId")
                        .HasDatabaseName("ix_handbook_item_handbook_id");

                    b.ToTable("handbook_item", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_phone_number");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_phone_number_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_phone_number_deleted_by_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_phone_number_number");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_phone_number_updated_by_id");

                    b.ToTable("phone_number", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.PositionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("InnerPositionId")
                        .HasColumnType("integer")
                        .HasColumnName("inner_position_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PhoneNumberId")
                        .HasColumnType("uuid")
                        .HasColumnName("phone_number_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<Guid?>("UserAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_position_assignment");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_position_assignment_created_by_id");

                    b.HasIndex("PhoneNumberId")
                        .HasDatabaseName("ix_position_assignment_phone_number_id");

                    b.HasIndex("UserAssignmentId")
                        .HasDatabaseName("ix_position_assignment_user_assignment_id");

                    b.ToTable("position_assignment", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.UserAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("PhoneNumberId")
                        .HasColumnType("uuid")
                        .HasColumnName("phone_number_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_assignment");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_assignment_created_by_id");

                    b.HasIndex("PhoneNumberId")
                        .HasDatabaseName("ix_user_assignment_phone_number_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_assignment_user_id");

                    b.ToTable("user_assignment", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("PositionAssignmentUser", b =>
                {
                    b.Property<Guid>("PositionAssignmentsId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_assignments_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasKey("PositionAssignmentsId", "UsersId")
                        .HasName("pk_position_assignment_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_position_assignment_user_users_id");

                    b.ToTable("position_assignment_user", (string)null);
                });

            modelBuilder.Entity("Contacts.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Contacts.Domain.Accounts.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_account_account_created_by_id");

                    b.HasOne("Contacts.Domain.Accounts.Account", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_account_account_deleted_by_id");

                    b.HasOne("Contacts.Domain.Accounts.Account", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_account_account_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Contacts.Domain.Handbook.Handbook", b =>
                {
                    b.OwnsMany("Contacts.Domain.Handbook.HandbookTranslation", "Translations", b1 =>
                        {
                            b1.Property<int>("HandbookId")
                                .HasColumnType("integer")
                                .HasColumnName("handbook_id");

                            b1.Property<int>("Language")
                                .HasColumnType("integer")
                                .HasColumnName("language");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("is_default");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("HandbookId", "Language")
                                .HasName("pk_handbook_translation");

                            b1.ToTable("handbook_translation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HandbookId")
                                .HasConstraintName("fk_handbook_translation_handbook_handbook_id");
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Contacts.Domain.Handbook.HandbookItem", b =>
                {
                    b.HasOne("Contacts.Domain.Handbook.Handbook", null)
                        .WithMany("Items")
                        .HasForeignKey("HandbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handbook_item_handbook_handbook_id");

                    b.OwnsMany("Contacts.Domain.Handbook.HandbookItemTranslation", "Translations", b1 =>
                        {
                            b1.Property<int>("HandbookItemId")
                                .HasColumnType("integer")
                                .HasColumnName("handbook_item_id");

                            b1.Property<int>("Language")
                                .HasColumnType("integer")
                                .HasColumnName("language");

                            b1.Property<string>("Alias")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("alias");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("is_default");

                            b1.HasKey("HandbookItemId", "Language")
                                .HasName("pk_handbook_item_translation");

                            b1.ToTable("handbook_item_translation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HandbookItemId")
                                .HasConstraintName("fk_handbook_item_translation_handbook_item_handbook_item_id");
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.PhoneNumber", b =>
                {
                    b.HasOne("Contacts.Domain.Accounts.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_phone_number_account_created_by_id");

                    b.HasOne("Contacts.Domain.Accounts.Account", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_phone_number_account_deleted_by_id");

                    b.HasOne("Contacts.Domain.Accounts.Account", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_phone_number_account_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.PositionAssignment", b =>
                {
                    b.HasOne("Contacts.Domain.Accounts.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_position_assignment_account_created_by_id");

                    b.HasOne("Contacts.Domain.PhoneNumbers.PhoneNumber", "PhoneNumber")
                        .WithMany("AssignedPositions")
                        .HasForeignKey("PhoneNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_phone_number_phone_number_id");

                    b.HasOne("Contacts.Domain.PhoneNumbers.UserAssignment", null)
                        .WithMany("PositionAssignments")
                        .HasForeignKey("UserAssignmentId")
                        .HasConstraintName("fk_position_assignment_user_assignment_user_assignment_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.UserAssignment", b =>
                {
                    b.HasOne("Contacts.Domain.Accounts.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_assignment_account_created_by_id");

                    b.HasOne("Contacts.Domain.PhoneNumbers.PhoneNumber", "PhoneNumber")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("PhoneNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_assignment_phone_number_phone_number_id");

                    b.HasOne("Contacts.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_assignment_user_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("PhoneNumber");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Contacts.Domain.Users.User", b =>
                {
                    b.HasOne("Contacts.Domain.Accounts.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Contacts.Domain.Users.User", "AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PositionAssignmentUser", b =>
                {
                    b.HasOne("Contacts.Domain.PhoneNumbers.PositionAssignment", null)
                        .WithMany()
                        .HasForeignKey("PositionAssignmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_user_position_assignment_position_assig");

                    b.HasOne("Contacts.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_assignment_user_user_users_id");
                });

            modelBuilder.Entity("Contacts.Domain.Handbook.Handbook", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.PhoneNumber", b =>
                {
                    b.Navigation("AssignedPositions");

                    b.Navigation("AssignedUsers");
                });

            modelBuilder.Entity("Contacts.Domain.PhoneNumbers.UserAssignment", b =>
                {
                    b.Navigation("PositionAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
